[profile.default]
src = "."
test = "test"
script = "script"
out = "out"
libs = ["lib", "node_modules"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./" }]
